# Generated by Django 3.2.9 on 2021-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_detials',
            field=models.ManyToManyField(blank=True, to='order.OrderStatus'),
        ),
    ]
