# Generated by Django 3.2.9 on 2021-11-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211114_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street',
        ),
    ]
